<a href="https://colab.research.google.com/github/Nerobite/Math_for_DS_Netologia/blob/main/Linear_algebra_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Задание 1

Создайте матрицу 3 на 3, заполненную числами от 1 до 9.

Прибавьте к ней матрицу с единицами на диагонале.

Умножьте полученную матрицу на вектор (1, 2, 3).

Вычислить транспонированную матрицу от полученной в результате прибавления матрицы.

Посчитайте обратную матрицу к полученной в результате прибавления матрице

In [11]:
A1 = np.arange(1, 10).reshape(3,3)

In [12]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
A2 = np.eye(3)

In [14]:
A2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
A3 = A1 + A2
A3

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [16]:
a = [1, 2, 3]

In [17]:
A3 @ a

array([15., 34., 53.])

In [18]:
#транспонированная матрица
np.transpose(A3)

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [19]:
#Обратная матрица
np.linalg.inv(A3)

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

Задание 2

Найдите собственные значения и собственные вектора матрицы:

m = np.array([[2, 2],
              [1, 3]])
print(m)


In [20]:
m = np.array([[2, 2], [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [21]:
np.linalg.eigvals(m)

array([1., 4.])

Задание 3
Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2!

In [24]:
a = np.array([[-1, -2, -1], [1, 1, 4], [2, 3, 6]])
print(a)
det = np.linalg.det(a)
print(det)

[[-1 -2 -1]
 [ 1  1  4]
 [ 2  3  6]]
1.0


In [25]:
det = 0

while det != 1:
    a = np.random.randint(-10,10,(3,3))
    det=np.linalg.det(a)

print('искомая матрица: \n',a)

искомая матрица: 
 [[-5 -1  5]
 [ 5  2 -7]
 [ 3 -1  0]]
