<a href="https://colab.research.google.com/github/Nerobite/Math_for_DS_Netologia/blob/main/math_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Домашнее задание "Основные математические понятия".


In [ ]:
import numpy as np
import sympy as sym

Задание 1:
Представим фильмы в виде бинарных векторов (numpy array) используя следующие признаки:

[Комедия, Боевик, Исторический, Бред Питт, Бенедикт Камбербэтч, Квентин Тарантино]

In [ ]:
film_1 = np.array([0,0,0,0,1,0])      # Игра в имитацию

film_2 = np.array([0,1,0,1,0,0])      # Ярость

film_3 = np.array([0,0,1,1,1,0])      # 12 лет рабства

film_4 = np.array([1,0,0,1,0,1])      # Однажды в Голливуде

Задание 1
Найти угол между векторами-фильмами "Ярость" и "12 лет рабства". Результатом будет являться косинусная мера, которую можно использовать для определения похожести векторов.

In [ ]:
#найдем скалярное произведение
np.dot(film_2, film_3)

1

In [ ]:
#найдем угол между векторами, для начала находим Евклидову норму
np.linalg.norm(film_2)

1.4142135623730951

In [ ]:
np.linalg.norm(film_3)

1.7320508075688772

In [ ]:
np.linalg.norm(film_2)*np.linalg.norm(film_3)

2.4494897427831783

In [ ]:
# cos угла между векторами
np.dot(film_2, film_3)/(np.linalg.norm(film_2)*np.linalg.norm(film_3))

0.40824829046386296

In [ ]:
#конвертируем полученное значение в величену угла, в радианах
np.arccos(np.dot(film_2, film_3)/(np.linalg.norm(film_2)*np.linalg.norm(film_3)))

1.1502619915109316

In [ ]:
#конвертируем в градусы
np.rad2deg(np.arccos(np.dot(film_2, film_3)/(np.linalg.norm(film_2)*np.linalg.norm(film_3))))

65.90515744788931

In [ ]:
#Угол между векторами равен 65,9 градусов, что показывает, что фильмы между собой похожи, но не очень сильно

Задание 2
Вычислить с помощью Python значение первой производной для функции 8x(x+3)**2
 в точке x = 1

In [ ]:
x = sym.Symbol('x')

In [ ]:
8*x*(x+3)**2

8*x*(x + 3)**2

In [ ]:
res = sym.diff(8*x*(x+3)**2, x)

In [ ]:
res

8*x*(2*x + 6) + 8*(x + 3)**2

In [ ]:
res.subs(x, 1)

192

In [ ]:
#Производная функции равна 192

Задание 3
Объединить векторы фильмов в матрицу, где каждый вектор является строкой матрицы. Умножьте вектор [1,2,3,4] на полученную матрицу

In [ ]:
matrix = np.array([film_1, film_2, film_3, film_4])

In [ ]:
matrix

array([[0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 0],
       [0, 0, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1]])

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.dot(matrix)

array([4, 2, 3, 9, 4, 4])